# Generated by Django 5.0.6 on 2024-05-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0003_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
