# Generated by Django 5.0.6 on 2024-05-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0004_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthdate',
            field=models.DateField(blank=True, default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
